import { Job, Candidate } from "./types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Backend Engineer",
    location: "San Francisco, CA",
    workType: "Hybrid",
    reqId: "ENG-2024-001",
    status: "Open",
    candidateCount: 142,
    lastSync: "2 hours ago",
    syncMode: "all",
    syncStages: [],
  },
  {
    id: "2",
    title: "Product Designer",
    location: "New York, NY",
    workType: "Remote",
    reqId: "DES-2024-003",
    status: "Open",
    candidateCount: 89,
    lastSync: "1 day ago",
    syncMode: "specific",
    syncStages: ["Phone Screen", "Onsite", "Offer"],
  },
  {
    id: "3",
    title: "Engineering Manager",
    location: "Austin, TX",
    workType: "Onsite",
    reqId: "MGR-2024-002",
    status: "Open",
    candidateCount: 56,
    lastSync: "3 days ago",
    syncMode: "none",
    syncStages: [],
  },
  {
    id: "4",
    title: "Data Scientist",
    location: "Seattle, WA",
    workType: "Remote",
    reqId: "DATA-2024-001",
    status: "Closed",
    candidateCount: 234,
    lastSync: "1 week ago",
    syncMode: "all",
    syncStages: [],
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: "1",
    name: "Sarah Chen",
    currentRole: "Staff Engineer at Meta",
    stage: "Onsite",
    location: "San Francisco, CA",
    experience: "8 years",
    skills: ["Python", "Go", "Kubernetes", "System Design"],
    leadership: "Led team of 12",
    background: "Ex-Google, Stanford CS",
    score: 95,
    reason: "Exceptional match with strong technical skills, leadership experience at FAANG companies, and local to SF.",
    email: "sarah.chen@email.com",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    currentRole: "Senior SWE at Stripe",
    stage: "Hired",
    location: "San Francisco, CA",
    experience: "6 years",
    skills: ["Python", "Java", "AWS", "Microservices"],
    leadership: "Tech lead for 8",
    background: "Ex-Amazon, Berkeley",
    score: 92,
    reason: "Strong technical background with payment systems expertise and proven leadership abilities.",
    email: "marcus.j@email.com",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    currentRole: "Backend Lead at Airbnb",
    stage: "Phone Screen",
    location: "Remote (Austin)",
    experience: "7 years",
    skills: ["Python", "Rust", "Docker", "PostgreSQL"],
    leadership: "Managed 5 engineers",
    background: "Ex-Uber, MIT",
    score: 87,
    reason: "Solid experience but remote location may require adjustment. Strong technical skills.",
    email: "emily.r@email.com",
  },
  {
    id: "4",
    name: "David Kim",
    currentRole: "SWE III at Microsoft",
    stage: "Offer",
    location: "Seattle, WA",
    experience: "5 years",
    skills: ["Python", "C#", "Azure", "TypeScript"],
    leadership: "Mentored 3 juniors",
    background: "Microsoft, UW",
    score: 78,
    reason: "Good skills but limited leadership experience. Would need relocation.",
    email: "david.kim@email.com",
  },
  {
    id: "5",
    name: "Jessica Park",
    currentRole: "Software Engineer at Coinbase",
    stage: "Phone Screen",
    location: "New York, NY",
    experience: "4 years",
    skills: ["Python", "JavaScript", "React", "Web3"],
    leadership: "Individual contributor",
    background: "Coinbase, NYU",
    score: 65,
    reason: "Developing skills but lacks senior-level experience and leadership background.",
    email: "jessica.p@email.com",
  },
  {
    id: "6",
    name: "Alex Thompson",
    currentRole: "Junior Developer at Startup",
    stage: "Rejected",
    location: "Chicago, IL",
    experience: "2 years",
    skills: ["Python", "SQL", "Django"],
    leadership: "None",
    background: "Bootcamp grad",
    score: 42,
    reason: "Insufficient experience for senior role. Would be better suited for mid-level position.",
    email: "alex.t@email.com",
  },
];

export const candidateStages = ["Phone Screen", "Onsite", "Offer", "Hired", "Rejected"];

export const quickSuggestions = [
  "5+ years experience",
  "Strong Python skills",
  "FAANG background",
  "Leadership experience",
  "SF Bay Area",
];

